update the scripts and info yml

diff --git a/.github/workflows/ci-info.yml b/.github/workflows/ci-info.yml
--- a/.github/workflows/ci-info.yml
+++ b/.github/workflows/ci-info.yml
@@ -54,13 +54,14 @@ jobs:
         run: |
           PLAIN_VERSION="$(./.github/scripts/get-version)"
           PULUMI_VERSION="${PLAIN_VERSION}"
+          echo "Pulumi version $PULUMI_VERSION"
 
           if [ "$IS_SNAPSHOT" = "true" ]; then
             TIMESTAMP=$(date +%s)
             PULUMI_VERSION="${PULUMI_VERSION%-*}-alpha.$TIMESTAMP"
           fi
 
-          ./.github/scripts/set-output version "${PULUMI_VERSION}"
+          echo "version=$PULUMI_VERSION" >> "$GITHUB_OUTPUT"
       - uses: ./.github/actions/retry
         with:
           action: jdx/mise-action@v2
@@ -78,14 +79,22 @@ jobs:
       - name: Extract release notes
         id: notes
         run: |
+          if [[ -z "${{ steps.version.outputs.version }}" ]]; then
+            echo "It's an empty output version "
+            exit 1
+          fi
+
           CHANGELOG="$(changie batch "${{ steps.version.outputs.version }}" --dry-run)"
-          ./.github/scripts/set-output release-notes "${CHANGELOG}"
+          echo "release-notes="$CHANGELOG"" >> "$GITHUB_OUTPUT"
+          #./.github/scripts/set-output release-notes "${CHANGELOG}"
       - name: Check version
         if: ${{ !inputs.is-snapshot }}
         run: |
           PULUMI_VERSION="${{ steps.version.outputs.version }}"
 
-          ./.github/scripts/update-versions "${PULUMI_VERSION}"
+          echo "pulumi version $PULUMI_VERSION"
+          bash ./.github/scripts/update-versions "${PULUMI_VERSION}"
+          echo "Script later"
 
           ERROR=false
           if [ -n "$(git status --porcelain)" ]; then
@@ -95,6 +104,7 @@ jobs:
             git diff
             echo "::endgroup::"
           fi
+          echo "after porcelain erro ris $ERROR"
 
           if EXISTING_RELEASE_DRAFT="$(gh release view "v${PULUMI_VERSION}" --json isDraft --jq '.isDraft')"; then
             if [ "$EXISTING_RELEASE_DRAFT" != "true" ]; then
