Update failure stmt

diff --git a/.github/workflows/ci-info.yml b/.github/workflows/ci-info.yml
--- a/.github/workflows/ci-info.yml
+++ b/.github/workflows/ci-info.yml
@@ -46,12 +46,14 @@ jobs:
           fetch-depth: 0
       - name: Print rate limits
         id: get_latest_release
-        continue-on-error: true
+        #continue-on-error: true
         run: |
           gh api -i repos/${{ github.repository }}/releases/latest
       - name: Report the status of last command
         if: ${{ steps.get_latest_release.outcome == 'failure' }}
-        run: echo "Getting the lastest release of repo ${{ github.repository }} failes!" 
+        run: |
+            echo "Getting the lastest release of repo ${{ github.repository }} fails!" 
+            exit 1;
       - name: Compute version
         id: version
         env:
